<?php

$info_turisme = array(
                    array(
                        "nom" => "Casa Museu Dalí",
                        "descripcio" => "Els orígens de la casa museu Dalí es remunten al 1930 quan Salvador Dalí i Domènech compra una petita barraca a una viuda d’un pescador i la remodela per poder-se instal·lar amb la seva esposa Gala. A partir de la primera barraca ja remodelada, va adquirint les cases del costat fins que obtenim la actual casa de Dalí. On l'excèntric pintor va treballar durant 50 anys.<br><br>Després de la mort de Gala l’any 1982, Dalí decideix no tornar més a la casa de Portlligat. Amb la mort del pintor al 1989, es decideix fer un petit recinte museístic que serà inaugurat al 1994. El museu és adaptat per els arquitectes Oriol Clos i Costa i José Ramos Illàn.<br><br>Actualment la casa esta dividida en tres espais. Primer les habitacions on Dalí va passar els moments més íntims, després el taller i en tercer lloc es troben els espais a l’aire lliure dissenyats per fer vida publica.<br><br>La Casa Salvador Dalí de Portlligat es un dels tres elements del triangle dalinià, juntament amb el Castell Gala Dalí Púbol i el Teatre-Museu Dalí Figueres.",
                        "direccio" => "",
                        "poblacio" => "Portlligat (Cadaqués)",
                        "telefon" => 972251015,
                        "lat" => "42.29322",
                        "lng" => "3.285975",
                        "horari" =>"11/07 - 30/09 De dilluns a diumenge	De 09.30 a 20.30 h. <br>01/10 – 01/11 De dimarts a diumenge	De 10.30 a 18.00 h",
                        "preu" => "14€",
                        "web" => "www.salvador-dali.org",
                        "email" => "reserves@fundaciodali.org",
                        "imatge" => "dali_portlligat.jpg"
                    ),
                    array(
                        "nom" => "Teatre-Museu Dalí",
                        "descripcio" => "El Teatre-Museu Dalí es troba sobre les restes de l’antic teatre municipal de Figueres, dissenyat per l’arquitecte Roca i Bros, va ser construït al 1850 però va ser destruït per un incendi durant la guerra civil espanyola, l’any 1939. <br><br>Dalí va elegir aquest edifici per exposar la seva obra per tres raons: la primera, perquè era un pintor eminentment teatral; la segona, perquè el Teatre es troba al davant de l'església on va ser batejat; i la tercera, perquè precisament fou en la sala del vestíbul del Teatre on vaig exposar la seva primera mostra de pintura. <br><br>Ell mateix el va dissenyar durant una dècada fins convertir-lo en realitat i va ser inaugurat l’any 1974, l’any 1989, quan Dalí mori van decidir enterrar les seves restes dins al museu. <br><br>Actualment i podem trobar bastantes obres de renom del artista alt-empordanès, com poden ser: la festa de l’ermita, la imatge desapareix, galarina, entre d’altres. ",
                        "direccio" => "Plaça Gala i Salvador Dalí, 5",
                        "poblacio" => "Figueres",
                        "telefon" => 972677505,
                        "lat" => "42.2805187",
                        "lng" => "2.9827328",
                        "horari" =>"11/07 - 30/09 De dimarts a diumenge	De 10.30 h a 18 h. <br>01/10 – 28/02 De dimecres a diumenge De 10.30 h a 15 h",
                        "preu" => "13€",
                        "web" => "www.salvador-dali.org",
                        "email" => "reserves@fundaciodali.org",
                        "imatge" => "museu_dali.jpg"
                    ),
                    array(
                        "nom" => "Castell Gala-Dalí",
                        "descripcio" => "El Castell Gala Dalí de Púbol, obert al públic des del 1996, permet descobrir un edifici medieval on Salvador Dalí va materialitzar un desbordant esforç creatiu pensant en una persona: Gala, i en una funció, un lloc adient per al descans i el refugi de la seva esposa. El pas del temps va determinar la transformació d'aquest espai, entre 1982 i 1984, en el darrer taller de Salvador Dalí i en el mausoleu per a la seva musa.<br><br>Documentat des del segle XI, l'estructura bàsica de l'actual edifici, de tres plantes i articulat al voltant d'un pati alt i estret, cal situar-la durant el període de màxima esplendor de la baronia de Púbol: la segona meitat del segle XIV i principi del XV.<br><br>Quan Dalí va comprar el Castell, el 1969, estava molt deteriorat, amb sostres caiguts, esquerdes importants i el jardí en estat semisalvatge. Tot això atorgava al conjunt un aspecte romàntic que és el que els Dalí valoraren i intentaren mantenir en la restauració que van encomanar. Es va consolidar l'aspecte ruïnós exterior, sense amagar les cicatrius provocades pel pas del temps.  Salvador Dalí  va utilitzar de manera molt intel·ligent les parets i els sostres semiderruïts, creant espais insospitats i de dimensions molt contrastades; va concebre la decoració interior basant-se en representacions pictòriques als murs, falses arquitectures, barroquisme tèxtil, antiguitats, simbologia de caire romàntic,... El resultat és un lloc tancat, misteriós, privat, auster i sobri, amb espais de gran bellesa, com ara l'antiga cuina convertida en cambra de bany o el Saló del Piano.",
                        "direccio" => "Gala Dali, s/n",
                        "poblacio" => "Púbol",
                        "telefon" => 972488655,
                        "lat" => "42.0146004",
                        "lng" => "2.9810561",
                        "horari" =>"11/07 - 30/09 De dimarts a diumenge	De 10:30 a 14 h	De 15:30 a 19:30.<br>01/10 – 10/01 De dimecres a diumenge De 10:30 a 15 h",
                        "preu" => "8€",
                        "web" => "www.salvador-dali.org",
                        "email" => "reserves@fundaciodali.org",
                        "imatge" => "castell_dali.jpg"
                    ),
                    array(
                        "nom" => "Basílica Santa Maria",
                        "descripcio" => "La Basílica gòtica de Santa Maria té una estructura i unes dimensions pròpies d’una catedral, una dignitat que no va aconseguir malgrat els diversos intents, en aquest sentit, dels comtes d’Empúries. És un dels exemples més interessants de l’arquitectura religiosa gòtica de Catalunya.<br><br>L’obra, començada al segle XIII, prosseguí durant tot el segle XIV i finalitzà a l’inici del XV, quan es construí la façana amb la bella portalada de marbre. L’espai interior, paradigma del gòtic mediterrani, conté les singulars fonts baptismals , el molt notable retaule major d’alabastre del segle XV, dos sarcòfags comtals i un vitrall gòtics, el retaule dels Dolors del segle XVIII, l’orgue del segle XIX i molts altres elements d’interès.<br><br>El campanar, amb decoració gòtica, segueix encara la composició arquitectònica dels campanars romànics d’influència llombarda. Pertany segurament al segle XIII.",
                        "direccio" => "Plaça Mossèn Cinto Verdaguer",
                        "poblacio" => "Castelló d'Empúries",
                        "telefon" => 688331094,
                        "lat" => "42.2594473",
                        "lng" => "3.0735595",
                        "horari" =>"De Setmana Santa  a 30 de juny i de l’1 de setembre al 3o de setembre De dilluns a diumenge 10-14h / 16-19h. <br>Del 1 novembre a setmana Santa De dilluns a diumenge 10-14h / 16-18h",
                        "preu" => "2,5€",
                        "web" => "www.basilicasantamaria.com",
                        "email" => "reserves@basilicasantamaria.com",
                        "imatge" => "basilica_santamaria.jpg"
                    ),
                    array(
                        "nom" => "Monestir de Sant Pere de rodes",
                        "descripcio" => "El Monestir de Sant Pere de Rodes s’aixeca en un dels cims de la Serra de Rodes, una cadena a primera línia de mar al nord de l’Alt Empordà. És un dels nombrosos testimonis de l’arquitectura romànica catalana, però potser és un dels més sofisticats arquitectònicament.<br><br>Del segle XI al XIV va ser el principal centre espiritual del comtat d’Empúries i el seu esplendor es mostra en les grans dimensions del conjunt monacal. Aquest està format per l’església, el campanar, el claustre, les sagristies, les dependències convencionals per fer-hi vida i el Palau de l’Abat.<br><br>El monestir està construït en terrasses per adaptar-se al terreny i els diversos edificis s’organitzen al voltant del claustre i l’església, aixecada entre els segles X i XI. En aquests dos edificis s’hi pot apreciar una mostra excepcional de l’escultura romànica: les columnes (originals de l’antiguitat) i els capitells que les coronen ens parlen de la marcada influència clàssica que té aquesta singular església.<br><br>A l’exterior, la portalada, a càrrec del Mestre de Cabestany, mostrava diferents escenes de la vida de Crist esculpides en marbre blanc. Els escassos fragments que han arribat fins a nosaltres ens donen mostra de la seva extraordinària qualitat, probablement una de les millors de la seva època.<br><br>Des del monestir es pot gaudir d’una de les millors vistes del Cap de Creus. Poc abans d'arribar-hi, hi ha les restes del poble medieval de Santa Creu de Rodes, entre les quals destaca l'església de Santa Helena de Rodes.",
                        "direccio" => "Camí del Monestir, s/n",
                        "poblacio" => "Port de la selva",
                        "telefon" => 972387559,
                        "lat" => "42.3233925",
                        "lng" => "3.1641821",
                        "horari" =>"De l'1 d'octubre al 31 de maig: de 10.00 a 17.30 h.<br>De l'1 de juny al 30 de setembre: de 10.00 a 20.00 h.",
                        "preu" => "6€",
                        "web" => "",
                        "email" => "santperederodes.cultura@gencat.cat",
                        "imatge" => "sant-pere-rodes.jpg"
                    ),
                    array(
                        "nom" => "Museu de l'Empordà",
                        "descripcio" => "El Museu de l'Empordà és una institució dirigida a la recerca, conservació i difusió del patrimoni cultural local i comarcal, amb un ampli programa d’exposicions i activitats. Ofereix al públic una lectura històrica de les seves col·leccions i una especial dedicació a la creació artística contemporània. Disposa de servei educatiu i de publicacions, biblioteca i sala de projeccions.<br><br>Amb una història que es remunta a 1885, amb l’arribada dels primers dipòsits del Museu del Prado, reuneix una interessant col·lecció d'art amb obres de relleu dins el panorama artístic català (Sorolla, Casas, Nonell, Sacharoff, Tàpies, Torres Monsó, Zush o Pazos) i empordanès (Dalí, Santos, Reig, Vallès, Planells, Massanet, Gabriel o Mitjà).<br><br>El fons es completa amb les col·leccions d’arqueologia, art medieval i pintura barroca. Creat l'any 1946, l’edifici es va inaugurar el 1971. Des de 1998 està gestionat per un consorci format per l'Ajuntament de Figueres, el Consell Comarcal de l'Alt Empordà i la Fundació Gala-Salvador Dalí. A partir de 2015 es dissol el Consorci i es recupera la gestió per part de l’Àrea de Cultura de l’Ajuntament de Figueres.",
                        "direccio" => "La Rambla, 2",
                        "poblacio" => "Figueres",
                        "telefon" => 972502305,
                        "lat" => "42.2666543",
                        "lng" => "2.9598233",
                        "horari" =>"De maig a octubre: de dimarts a dissabte d’11.00 a 20.00 hores; diumenge i festius, d’11.00 a 14.00 hores. <br>De novembre a abril: de dimarts a dissabte d’11.00 a 19.00 hores; diumenge i festius, d’11.00 a 14.00 hores",
                        "preu" => "4€",
                        "web" => "www.museuemporda.org",
                        "email" => "infome@museuemporda.org",
                        "imatge" => "museu-emporda.jpg"
                    ),array(
                        "nom" => "Museu del Joguet",
                        "descripcio" => "És un casal projectat l'any 1767 per Pere M. Cermeño, el mateix enginyer que va construir el Castell de Sant Ferran. Fou reformat com a hotel l'any 1931 per l'arquitecte Pelai Martínez Paricio. El 1982 s'inaugura el Museu del Joguet de Catalunya, remodelat l'any 1998. <br><br>A partir de l'aportació inicial de Josep Maria Joan i Rosa, un col·leccionista de joguines, el museu actual exhibeix més de 4000 peces: zoòtrops, mecanos, teatrins, animals i cavalls de cartró, cuines, pilotes, baldufes, avions, cotxes, trens, nines, titelles, aparells de màgia, jocs per a invidents, disfresses, retallables, manubris, soldats, robots, màquines de vapor, ossets, tricicles, patinets... Moltes d'aquestes peces s'acompanyen de fotografies antigues de nens amb els seus joguets, la qual cosa ens ajuda a situar-les cronològicament i a veure com s'hi jugava. Alguns joguets havien pertangut a personatges com Anna Maria i Salvador Dalí, Federico García Lorca, Joan Miró, Carles Fages de Climent, Josep Palau i Fabre, Joan Brossa, Quim Monzó, Frederic Amat...",
                        "direccio" => "Carrer de Sant Pere, 1",
                        "poblacio" => "Figueres",
                        "telefon" => 972504585,
                        "lat" => "42.266631",
                        "lng" => "2.9608155",
                        "horari" =>"D'OCTUBRE a MAYO:<br> De martes a viernes: de 10 a 18.30 h <br> Sábados: de 10.30 a 19.30 h <br> Domingos y festivos: de 10.30 a 14.30 h <br>JUNY a SEPTEMBRE: <br> De lunes a viernes: de 10.30 a 19 h <br> Sábados: de 10.30 a 20 h <br> Domingos: de 10.30 a 14.30 h",
                        "preu" => "7€",
                        "web" => "www.mjc.cat",
                        "email" => "info@mjc.cat",
                        "imatge" => "joguet.jpg"
                    ),array(
                        "nom" => "Castell de Requesens",
                        "descripcio" => "Prop de la frontera amb França, a la Jonquera, i al cim d'un turó de la Serra de l'Albera, es troba el Castell de Requesens. Aquest imponent castell va ser construït al segle XI, i ha estat objecte d'innombrables disputes territorials i l'escenari de setges i batalles fins al segle XVI. Durant aquests cinc segles va canviar de mà diverses vegades, ja sigui per ocupació, donació o herència, fins al seu abandonament al segle XVI, ja que no va oferir garanties davant el poder de l'artilleria.<br><br>A finals del segle XIX, el seu llavors propietari Tomás de Rocabertí, comte de Peralada, va decidir reconstruir-la per convertir-la en la seva residència d'estiu. Va encarregar l'obra de l'arquitecte Alexandre Comalat, que es va inspirar en les reconstruccions dels castells francesos de l'època, va fer una gran obra de reconstrucció intentant ser el més fidel possible al castell original. Tomás de Rocabertí va morir el 1898, abans de veure l'obra acabada, i no deixar fills. El castell va ser heretat per la seva germana Joana Adelaida, que va continuar les obres. El castell es va inaugurar el 24 de juny de 1899 amb un gran festival. Cinc dies després de l'inaguaració la comtessa va ser trobada morta en estranyes circumstàncies. Tampoc va deixar fills, de manera que el castell va ser heretat per un parent mallorquí, el marquès de la Torre, que el 1913 va vendre als germans mallorquins que es dedicaven a l'explotació dels boscos de la Vall de Requesens, i aquests, al seu torn, el van vendre el 1924 a la dona del duc d'Infantado, que el va vendre el 1942 a l'empresa Societat Bors S.A.<br><br>El 1955 fou venut als socis Ramon Esteba i Colomer (industrial natural d'Anglès) i Josep Pijoan, els descendents dels quals encara el posseeixen.",
                        "direccio" => "Camí a Requesens, s/n",
                        "poblacio" => "Els límits",
                        "telefon" => 646179509,
                        "lat" => "42.4466413",
                        "lng" => "2.9422036",
                        "horari" =>"Només obrirem prèvia reserva d’una visita guiada.",
                        "preu" => "7€",
                        "web" => "www.fincaderequesens.cat",
                        "email" => "conxitaesteba@gmail.com",
                        "imatge" => "requesens.jpg"
                    ),array(
                        "nom" => "Empúries",
                        "descripcio" => "Empúries és l’únic jaciment arqueològic de la Península Ibèrica on conviuen les restes d’una ciutat grega Empòrion amb les d’una ciutat romana, Emporiae. És també la porta d’entrada de la cultura clàssica: 10 segles d’història que van transformar per sempre els antics pobles ibers que hi habitaven.<br><br>El primer establiment dels grecs va ser al segle VI aC en una petita illa davant de la costa del golf de Roses (Palaia Polis, ciutat antiga), tot i que després es van desplaçar a terra ferma per fundar el que es coneix com la Neàpolis, ciutat nova. L’any 218 aC, el port emporità va servir de punt d’entrada a la Península per a les tropes romanes en la seva lluita contra l’exèrcit cartaginès. Entre els segles VI aC i V dC, Empúries ha estat port, enclavament comercial, colònia occidental de Grècia, primer campament romà de la Península, pròspera ciutat romana...<br><br>Les ruïnes gregues actuals pertanyen a la ciutat d'època hel·lenística. Durant la visita hi anirem trobant els recintes d'Asclepi i Serapis, la petita indústria on s'elaboraven conserves i salses de peix, l'Agorá o plaça pública i les restes de paviment d'una sala de banquets amb una inscripció en grec.<br><br>D’època romana destaca la Domus 1 amb els mosaics que decoraven el terra, la Insula 30 (zona ocupada per les termes públiques de la ciutat), el Fòrum, les restes de la Basílica i la Cúria i les tabernae o botigues.<br><br>A mig camí de l'itinerari es pot visitar el museu monogràfic de les excavacions d'Empúries que custodia l’excepcional escultura original d’Asclepi trobada al jaciment.<br><br>Es tracta doncs d’un espai privilegiat per entendre l’evolució de l’urbanisme grec i romà i un punt d’inflexió en la història de la Península Ibèrica. Actualment és una de les seus del Museu d’Arqueologia de Catalunya.",
                        "direccio" => "Puig i Cadafalch s/n",
                        "poblacio" => "L'Escala",
                        "telefon" => 972770208,
                        "lat" => "42.1339441",
                        "lng" => "3.109809",
                        "horari" =>"De l’1 d’octubre al 31 de maig (dl.-dg.) de 10h a 18h i De l’1 de juny al 30 de setembre (dl.-dg.) de 10h a 20h",
                        "preu" => "6€",
                        "web" => "www.macempuries.cat",
                        "email" => "macempuries.cultura@gencat.cat",
                        "imatge" => "Empuries.jpg"
                    ),array(
                        "nom" => "Aiguamolls de l'Empordà",
                        "descripcio" => "El Parc Natural dels Aiguamolls de l'Empordà és la segona zona humida més important de Catalunya, després del delta de l'Ebre, i un destacat lloc d'observació ornitològica.<br><br>Antigament aquests aiguamolls s'estenien per tota la plana de la badia de Roses i la del Baix Ter, de manera que el massís del Montgrí s'aixecava com una illa enmig de les aigües. Fins als anys setanta del segle passat, els aiguamolls s'havien degradat considerablement: les zones humides empordaneses anaven desapareixent a causa de l'excessiva urbanització i la creació d'equipaments turístics de tota mena. Per això, el 1976 es va engegar una campanya popular que lluitava per la recuperació d'aquests espais. Com a resultat, l'octubre del 1983 el Parlament de Catalunya els va declarar Paratge d'Interès Nacional i, un any i mig més tard, van ser declarats Parc Natural.<br><br>Gran part de les zones protegides corresponen al terme municipal de Castelló d'Empúries, però el parc també s'estén per altres municipis. Consta de tres zones de reserva natural integral: l'illa de Caramany, les Llaunes (llacunes litorals salobres) i els Estanys (entre els quals hi ha el de Vilaüt), i una zona de reserva parcial. En total abasta 4.960 hectàrees, a les quals s'afegeix una extensió marina declarada Espai Natural Protegit, de 5.868 hectàrees més.<br><br>Destaca per una biodiversitat molt rica, tant de flora com de fauna. Hi són especialment rellevants els ocells, tant els que hi viuen tot l'any com els que s'hi estan una temporada, en la seva ruta cap al sud, al final de l'estiu, o cap al nord, a la primavera. Així, el visitant hi pot identificar fàcilment diverses espècies d'ànecs, bernats pescaires, martinets i esplugabous, i hi pot veure planar l'arpella i eixugar-se el plomatge el corb marí i admirar l'elegància de les aus de potes llargues, com les grues, els flamencs, els camallargs i les conspícues cigonyes, reintroduïdes al parc als anys vuitanta. L'esforç humà per recuperar els últims aiguamolls de l'Empordà també ha portat a reintroduir-hi amb èxit altres espècies, com la polla blava i la llúdria.",
                        "direccio" => "Crta/ de Castelló d’Empúries a Sant Pere Pescador",
                        "poblacio" => "Castelló d’Empúries",
                        "telefon" => 972454222,
                        "lat" => "42.2247746",
                        "lng" => "3.089862",
                        "horari" =>"Obert cada dia de 9h a 16h (hivern) i de 9h a 18,30h (estiu).",
                        "preu" => "Gratis",
                        "web" => "aiguamollsdelemporda.cat",
                        "email" => "pnaiguamolls@gencat.cat",
                        "imatge" => "aiguamolls-de-l-emporda-girona.jpg"
                    ),array(
                        "nom" => "Ciutadella de Roses",
                        "descripcio" => "La Ciutadella és un bé Cultural d'Interès Nacional (BCIN) i jaciment arqueològic en continua investigació on es pot gaudir d'un complet itinerari senyalitzat i conèixer les diferents ocupacions històriques del lloc a través de les restes conservades, del s.IV a.c., data de la fundació de la colònia grega de Rhode, fins al s.XX.<br><br>La fortificació renaixentista clou un recinte que conté un jaciment arqueològic de cronologia molt àmplia, amb restes d'època antiga (barri hel·lenístic) i visigòtica o tardo-romana (edifici A). De la Roses medieval són presents el monestir i el nucli urbà que es desenvolupa al voltant amb els diferents perímetres de muralles, fins a la darrera fase, la d'època moderna, de les qual se'n conserven les restes de diferents edificis militars.",
                        "direccio" => "Av. de Rhode, s/n",
                        "poblacio" => "Roses",
                        "telefon" => 972151466,
                        "lat" => "42.2656785",
                        "lng" => "3.1705532",
                        "horari" =>"Hivern: de dimarts a dissabte, de 10 h a 17 h, i diumenges de 10 h a 14 h, Estiu: de dimarts a diumenge de 10 h a 20 h",
                        "preu" => "4€",
                        "web" => "www.rosescultura.cat",
                        "email" => "cultura@roses.cat",
                        "imatge" => "ciutadella.jpg"
                    ),array(
                        "nom" => "Castell de la Trinitat",
                        "descripcio" => "Bé Cultural d'Interès Nacional, el Castell de la Trinitat és un dels primers exemples de fortalesa d'artilleria de costa i un edifici innovador respecte a l'època en què va ser concebut i construït. Aixecat sobre un promontori que controla i defensa l’entrada per mar al port de Roses, el castell formava part de l’estratègia mediterrània de defensa que l’Imperi espanyol va impulsar durant l’època moderna.<br><br>El 1544 es van iniciar les obres de la seva construcció, per ordre del rei Carles I. El 1553 el perímetre murat ja està construït i faltava edificar l'interior. El responsable del projecte va ser l’enginyer militar Luís Pizaño que va idear una fórmula arquitectònica original per fer front a l’evolució i el perfeccionament de l’artilleria, a més de l’escenari bèl·lic de l’època. Roses, en ser dels primers llocs on es va intervenir, fou un camp de proves per l’experimentació d’un a nova arquitectura militar.<br><br>Aquest castell, popularment conegut com el de la Poncella o el Botó de Roses, presenta una planta en forma d’estrella de quatre puntes, anomenades punta de Roses (O), de la Trinitat (E), de les Medes (S) i de Sant Pere de Rodes (N), amb un cinquena punta afegida per protegir la via d’entrada al castell (revellí).<br><br>Després d'haver participat activament en les batalles dels diferents setges pels quals va passar la població i port de Roses durant els segles XVI, XVII i XVIII, el castell de la Trinitat va ser destruït definitivament el 1814. Aquest va ser objecte d’una voladura devastadora duta a terme pels anglesos que no podien protegir la guarnició que el defensava de l'atac de les tropes franceses.<br><br>Adquirit per l'Ajuntament l'any 1990, l'any 2011, després de 8 anys de treballs de restauració i rehabilitació, va ser obert al públic i integrat en el circuit patrimonial i d'equipaments culturals de Roses.",
                        "direccio" => "Carrer d'Antoni Canals, 105",
                        "poblacio" => "Roses",
                        "telefon" => 972151466,
                        "lat" => "42.2473743",
                        "lng" => "3.1837425",
                        "horari" =>"D'octubre a juny: dissabtes d'11 h a 17 h, i diumenges i festius d'11 h a 15 h.<br>Juliol, agost i septembre: de dilluns a diumenge de 17 h a 22 h",
                        "preu" => "5€",
                        "web" => "www.rosescultura.cat",
                        "email" => "cultura@roses.cat",
                        "imatge" => "trinitat.jpg"
                    ),array(
                        "nom" => "Castell de Sant Ferran",
                        "descripcio" => "El major monument de Catalunya és també la fortalesa abaluartada més gran d'Europa. El Castell de Sant Ferran ocupa 550.000 m² al capdamunt d’un turó de Figueres. Com a bon castell fronterer, la seva situació és immillorable: té bones panoràmiques de la Serra de l’Albera, que fa frontera amb França, i del golf de Roses.<br><br>Precisament es va aixecar davant la necessitat de reforçar la frontera després de la Pau dels Pirineus de 1659 i deu el seu nom al rei Ferran VI. La fortificació, inaugurada el 1766, però acabada de construir el 1892, està formada per dos recintes.<br><br>L’interior, de més de 325.000 m2, consta de sis baluards units per panys de muralla. No passa desapercebuda la magnitud de l’edifici: cavallerisses amb capacitat per a 500 cavalls, magatzems per guardar queviures per a 10.000 persones en un any, una gran plaça d’armes, nou pavellons per a l’allotjament de les autoritats i les seves famílies, i quatre grans cisternes amb una capacitat total de nou milions de litres d'aigua.<br><br>El recinte exterior, amb un perímetre de 3.120 metres, l’integren tres hornabecs, set revellins i dues contraguàrdies. Està separat de l’exterior per un gran fossat de 10 hectàrees, que actualment es pot visitar, incloses les galeries subterrànies.<br><br>Les seves monumentals dimensions han fet sempre difícil i molt costosa la seva activitat militar que freqüentment ha estat per sota de les seves possibilitats. Des del 1997 s’organitzen visites guiades regulars al Castell de Sant Ferran.",
                        "direccio" => "Pujada del Castell, s/n",
                        "poblacio" => "Figueres",
                        "telefon" => 972506094,
                        "lat" => "42.2735818",
                        "lng" => "2.9462781",
                        "horari" =>"De l’últim diumenge d’octubre fins últim diumenge de març de 10:30 a 15:00.  Setmana Santa (dimarts a diumenge) i temporada d’estiu (de l’1 de juliol al 15 de setembre) de 10:00 a 20:00.",
                        "preu" => "3€",
                        "web" => "lesfortalesescatalanes.info",
                        "email" => "dif@lesfortalesescatalanes.info",
                        "imatge" => "CastSanFerr.jpg"
                    ),array(
                        "nom" => "Casc Historic Sant llorenç de la Muga",
                        "descripcio" => "El lloc de Sant Llorenç de la Muga és documentat ja al segle X amb el nom «Santi Laurenti de Sambuca», encara que hom creu que ja era habitat en època romana.[1] El nucli històric actual fou fortificat vers els segles XIV-XV, conservant avui en dia el traçat de la muralla format per quatre torres i tres portals, creant un recinte de forma gairebé triangular.<br><br>Al llarg del segle XVIII la població es desenvolupà gràcies a l'activitat menestral de paraires i cardadors. Sota el regnat de Carles III, s'explotaren les mines de ferro i plom, fundant diverses fargues, com la Farga Reial de Sant Sebastià, dedicada a l'elaboració de munició. Al maig de l'any 1794 va ser destruïda pel general francès Pierre François Charles Augereau i les seves tropes, en la Batalla de Sant Llorenç de la Muga, durant la Guerra Gran.<br><br>Les ruïnes d'aquesta fosa estan cobertes actualment pel pantà de Darnius-Boadella. Els elements més destacats del nucli són el Castell medieval de Sant Llorenç, amb les diferents torres, portals i trams de muralles de la fortificació, l'Església romànica de Sant Llorenç i les diferents carrers i cases d'origen medieval i d'època moderna.",
                        "direccio" => "",
                        "poblacio" => "Sant llorenç de la Muga",
                        "telefon" => 972569140,
                        "lat" => "42.3212631",
                        "lng" => "2.7832399",
                        "horari" =>"Obert 24 hores",
                        "preu" => "Gratuit",
                        "web" => "ca.xn--santllorendelamuga-hvb.cat",
                        "email" => "",
                        "imatge" => "s_muga.jpg"
                    ),array(
                        "nom" => "Ruines d'Ullestret",
                        "descripcio" => "El poblat ibèric del puig de Sant Andreu d’Ullastret és el més gran de Catalunya. Es considera que fou una autèntica ciutat, capital de la tribu ibera que els autors antics anomenaren indiketes. El primer poblat ibèric d’Ullastret data de la primera meitat del segle VI aC, tot i que la zona s’ha relacionat amb assentaments anteriors, de la primera edat del ferro. Es tracta d’un poblat aturonat i fortificat amb una gran muralla, que permetia controlar tot el paisatge circumdant.<br><br>El poblat forma part d’un conjunt arqueològic d’època ibèrica més extens, del qual coneixem un altre poblat, una necròpolis, i un seguit de petits assentaments dispersos pel territori.<br><br>La visita al jaciment ibèric d’Ullastret es completa amb la visita al museu, on s’exposen les troballes arqueològiques més destacades del conjunt arqueològic.",
                        "direccio" => "Afores, s/n, puig de Sant Andreu",
                        "poblacio" => "Ullestret",
                        "telefon" => 972179058,
                        "lat" => "42.005711",
                        "lng" => "3.079392",
                        "horari" =>"Horari d’hivern: de l’1 d’octubre al 31 de maig <br>De dimarts a diumenge: de 10 a 18h <br><br>Horari d’estiu: de l’1 de juny al 30 de setembre <br> De dimarts a diumenge: de 10 a 20h",
                        "preu" => "5€",
                        "web" => "www.macullastret.cat",
                        "email" => "macullastret.cultura@gencat.cat",
                        "imatge" => "Ullastret.jpg"
                    ),array(
                        "nom" => "Monestir de Porta Ferrada",
                        "descripcio" => "Per les dades històriques que coneixem hem de situar la fundació del Monestir Benedictí a la primera meitat del s. X. Es va triar la badia guixolenca per l'existència d'un bon port natural i la proximitat de la serralada costanera que facilitaria la fugida i donaria certa protecció en cas d'atacs marítims. També hi devia comptar el record de la llegenda del martiri de sant Feliu l'Africà a principis del s. IV així com, molt probablement, l'aprofitament d'algunes construccions anteriors d'època romana baiximperial com ara el mausoleu, del qual se’n conserven restes arqueològiques al basament de la Torre del Fum..<br><br>L'establiment benedictí va tenir una gran influència cultural i educadora. Era el centre que preservava el saber i el principal promotor de l'art. Sobresurt la personalitat de l'abat Arnau (1043-1052), monjo de Sant Miquel de Cuixà i amic íntim del bisbe-abat Oliva.<br><br>Al voltant de l'activitat del Monestir es va anar formant un raval. El barri va créixer fins a establir habitatges a l'altre costat de la riera, en el que serà l'embrió de la vila medieval, organitzada al voltant de la plaça del mercat. D'aquesta vila medieval en coneixem els trets essencials. Hi havia un nucli urbà envoltat de muralles, torres i portals, per protegir els habitants en un temps de guerres constants. Més enllà, fora muralles, hi havia el monestir-fortalesa, també emmurallat, amb el raval de la Riera. I, a l'altra banda, ja als afores, el raval de Tueda. Una mica més lluny, a Sant Amanç, hi havia un grup de masos dedicats al conreu de la terra.<br><br>Dins del recinte emmurallat hi deuria haver d'un a dos centenars de cases, petites, d'un sol estatge i d'un o dos pisos com a màxim, que donaven a uns carrers estrets i irregulars que confluïen a la plaça; és a dir, a un lloc públic més espaiós, rectangular i en part porticat, que esdevindria el centre polític i comercial de la població. A la plaça, hi vivien poques famílies però les que hi vivien eren importants.",
                        "direccio" => "Plaça del Monestir, s/n",
                        "poblacio" => "Sant Feliu de Guíxols",
                        "telefon" => 972821575,
                        "lat" => "41.7801197",
                        "lng" => "3.0262576",
                        "horari" =>"de 01 de juliol de 2020 a 31 d'agost de 2020 Cada dia de 10 h. a 19 h. <br>de 01 de setembre de 2020 a 31 de desembre de 2020 De dilluns a divendres de 10h. a 14.30h<br>Dissabtes de 10h. a 18h.<br>Diumenges i festius de 10h. a 14h.",
                        "preu" => "2€",
                        "web" => "museu.guixols.cat",
                        "email" => "",
                        "imatge" => "Porta_Ferrada.jpg"
                    ),array(
                        "nom" => "Castell del Montgrí",
                        "descripcio" => "És una fortalesa construïda entre 1294 i 1302. L'origen de la construcció del castell de Montgrí es troba en la rivalitat existent entre el rei Jaume II i els comtes d'Empúries. Es començà a construir per Bernat de Llabià, governador de Torroella, el 1294 com a punt de control per un enfrontament entre Jaume el Just i Ponç V, comte d'Empúries. La data d'inici de les obres es desprèn de l'escrit de Jaume II al seu procurador Bernat de Llevià, veí de Torroella, en el qual el rei li encarregava l'administració i direcció de les obres del castell. Per a la construcció es comptà amb les rendes reials de Torroella i un impost sobre els bous d'Ullà i Albons. Tres anys després, el mateix Bernat de Llevià va rebre la custòdia del castell.<br><br>Les obres es van interrompre el 1301 sense acabar-ne la construcció, degut a la consolidació del poder del comtat de Barcelona enfront del comtat d'Empúries. La pèrdua d'importància de la casa comtal emporitana va fer innecessari l'acabament de l'obra, encara que es coneix amb exactitud la data d'interrupció. Les darreres notícies que es tenen del castell daten del 1413, i el relacionen amb la família Llevià. Ja dintre del segle xx, l'abandó havia conduït l'edifici a una situació de degradació preocupant. El 10 de novembre de 1985 es féu una jornada popular de neteja a fi de conscienciar els organismes oficials de la necessitat de restaurar-lo. La Generalitat, la Diputació i l'Ajuntament encarregaren un projecte de consolidació i posteriorment fou aprovat el pressupost necessari per dur-lo a terme.<br><br>El castells de Bellcaire i del Montgrí encara es miren desafiants, tots dos són testimonis de la lluita aferrissada de la monarquia contra el poder feudal. La lluita acabà amb la incorporació del comtat a la corona, després d'ocasionar la ruïna de la comarca i la desviació del curs del Ter de la plana nord del Montgrí a la plana sud a la primera meitat del segle xiv. Aquesta desviació provocà la formació de les dunes continentals de Torroella.",
                        "direccio" => "Massís del Montgrí",
                        "poblacio" => "Torroella de Montgrí",
                        "telefon" => 972758112,
                        "lat" => "42.0521389",
                        "lng" => "3.1316312",
                        "horari" =>"Obert 24 hores",
                        "preu" => "Gratis",
                        "web" => "www.torroella-estartit.cat",
                        "email" => "",
                        "imatge" => "Castell_de_Montgrí.jpg"
                    ),array(
                        "nom" => "Castell de Begur",
                        "descripcio" => "Construït al segle XVI, el castell de Begur és un dels principals atractius turístics de la població i ha sigut declarat Bé Cultural d'Interès Nacional. Està situat dalt d'un promontori que domina tota la zona, a ple centre de la localitat. És la part més alta i ofereix unes vistes excel·lents de la costa.<br><br>La fortalesa va ser aixecada sobre la roca i conserva molts dels seus elements principals, sobretot la torre mestra de forma cilíndrica de 5 metres d'altura, que va ser construïda en el punt més elevat. També trobarem restes de murs que mantenen l'estructura d'un conjunt històric i imponent.",
                        "direccio" => "Passeig del Doctor Pericot, s/n",
                        "poblacio" => "Begur",
                        "telefon" => 972624520,
                        "lat" => "41.9564159",
                        "lng" => "3.2085339",
                        "horari" =>"Obert 24 hores",
                        "preu" => "Gratis",
                        "web" => "visitbegur.cat",
                        "email" => "turisme@begur.cat",
                        "imatge" => "Castell_begur.jpg"
                    ),array(
                        "nom" => "Claustre Mas del Vent",
                        "descripcio" => "El Mas del Vent originalment dit Mas Brugarol, se situa al nucli de la Fosca de Palamós – Costa Brava. La masia i la torre daten del segle XVI, dins de la finca està el claustre d’estètica romànica. En aquest singular espai es celebren esdeveniments com reunions d’empresa, casaments, sopars… Des de 2016 s'han obert les portes per a visites guiades en col·laboració amb l’Ajuntament de Palamós. Durant l’estiu es celebren visites teatralitzades, una experiència única que combina teatre i gastronomia.<br><br>Aquest edifici, reformat pels prestigiosos arquitectes RCR, està inclòs dins de l’Inventari del patrimoni Arquitectònic de Catalunya. El claustre va ser adquirit a la dècada dels anys 50 del segle passat per Hans Engelhorn. Una obra que ha provocat un intens debat intel·lectual sobre la seva autenticitat. A la finca destaquen escultures de Xavier Medina-Campeny i de Xavier Escribá.",
                        "direccio" => "Passatge Rutlla, 7",
                        "poblacio" => "Palamós",
                        "telefon" => 972600550,
                        "lat" => "41.8603531",
                        "lng" => "3.1373091",
                        "horari" =>"",
                        "preu" => "",
                        "web" => "www.brugarol.com",
                        "email" => "brugarol@brugarol.com",
                        "imatge" => "Claustre_de_Palamós.jpg"
                    ),array(
                        "nom" => "Monestir de Sant Miquel de Cruïlles",
                        "descripcio" => "L'església de Sant Miquel de Cruïlles, que data de la primera meitat del segle XI, fou dotada entre 1031 i 1057 pels senyors de Cruïlles. L'any 1057 la seva comunitat monàstica fou unida al monestir italià de S. Michele della Chiusa (Torí). L'any 1144 passà a dominar l'església parroquial de Santa Eulàlia de Cruïlles, i també en depengué el priorat de Sant Genís de Rocafort (Martorell), fundat vers el 1100. L'any 1485 el cenobi va ser saquejat pels remences. L'any 1592 el Papa l'incorporà a l'abadia gironina de Sant Pere de Galligants, quan ja només hi havia el prior i un sacerdot. El darrer prior fou Joaquim Ferrer de Sitjar (1580-1608). Posteriorment l'església passà a ser sufragània de Santa Eulàlia de Cruïlles. El 1835, arran de la desamortització, el monestir (tret de l'església) passà a mans particulars.<br><br>Amb la localització d'una part important dels fons documentals del monestir a l'Arxiu de la Corona d'Aragó, Elvis Mallorquí va iniciar una recerca sobre l'edició dels documents anteriors a 1300 acompanyada per un estudi sobre els primers segles d'història del monestir: la fundació, la constitució i la gestió del patrimoni territorial, la comunitat benedictina i la relació amb altres institucions eclesiàstiques –les parròquies, des de l'any 1144 va posseir la parròquia de Santa Eulàlia de Cruïlles i el priorat de Sant Genís de Rocafort, el bisbe, l'abadia de San Michele della Chiusa (Piemont, Itàlia)- i l'influx sobre els habitants de la vila formada a redós dels edificis del monestir. Durant el 2009 i 2010 es van restaurar i es va descobrir que són similars a les existents al Saló del Tinell de Barcelona.<br><br>Des de l'any 2008 i fins a l'actualitat, el Consell Comarcal del Baix Empordà, conjuntament amb altres administracions, ha iniciat diverses tasques de restauració de l'església. Les principals s'han centrat en l'assentament de l'estructura de l'edificació, l'eliminació d'humitats, la conservació i preservació de les pintures romàniques dels lleons i la traïció de Judes, i una intervenció arqueològica en extensió de les tres naus que conformen l'edifici. El 2009 es van descobrir unes pintures del segle XIII.",
                        "direccio" => "",
                        "poblacio" => "Cruïlles",
                        "telefon" => 972640573,
                        "lat" => "41.953967",
                        "lng" => "3.004780",
                        "horari" =>"",
                        "preu" => "",
                        "web" => "www.cmss.cat",
                        "email" => "",
                        "imatge" => "Cruïlles,_Església_de_Sant_Miquel.jpg"
                    ),array(
                        "nom" => "Casc Historic Pals",
                        "descripcio" => "Si hi ha un poble famós pel seu preciós nucli antic, aquest és Pals. Damunt de la mateixa roca es troba la torre romànica de les Hores, que corona el centre històric de Pals. Als peus de la torre, el casc antic es manté recollit en la seva antiga muralla medieval. Pels carrers més antics del municipi es troben  preciosos edificis gòtics i romànics, també alguns edificis arabescos i detalls barrocs. Un altre atractiu turístic són les tombes antropomòrfiques d’època visigoda, del carrer Major que daten del s.V-VI <br><br>El topònim de Pals ve del llatí, Palus, que significa terreny pantanós. Molts municipis de la Costa Brava han optat per seguir els passos de Pals i han restaurat curosament els seus preciosos centres històrics, una alternativa per visitar després d’un dia de platja o durant els mesos en què el clima no permet als turistes gaudir de les cristal·lines aigües de la Costa Brava. <br><br>El conjunt medieval de Pals ha estat guardonat amb el Premi Nacional de Belles Arts (1973), amb el Premi Nacional de Belles Arts i Turisme (1980) i la Medalla d’Honor del Turisme de Catalunya (1986).<br><br>El casc antic de Pals va quedar molt danyat durant la Guerra Civil Espanyola, però gràcies a subvencions, sobretot per part de la Diputació de Girona, es va dur a terme un minuciós procés de restauració que es va començar el 1948 i va acabar 30 anys més tard.",
                        "direccio" => "",
                        "poblacio" => "Pals",
                        "telefon" => 972637380,
                        "lat" => "41.9851158",
                        "lng" => "3.135968",
                        "horari" =>"Obert 24 hores",
                        "preu" => "Gratis",
                        "web" => "www.visitpals.com",
                        "email" => "info@pals.cat",
                        "imatge" => "pals.jpg"
                    ),array(
                        "nom" => "Casc Historic Peratallada",
                        "descripcio" => "La vila, declarada conjunt històrico-artístic i bé cultural d'interès nacional (BCIN), és un dels nuclis més importants de Catalunya pel que fa a arquitectura medieval. D'un extraordinari atractiu i bellesa, conserva el seu antic aspecte feudal, amb carrers empedrats i estrets, amb nombrosos entrants i sortints. El recorregut pel poble permet descobrir diferents punts de vista del castell-palau, les muralles i un conjunt d’arquitectura popular. La població es troba assentada tota ella, damunt la roca de gres, treballada de diverses maneres. No hi ha dubte que el més impressionant són les valls de les muralles, fossat excavat a la roca viva.<br><br>Així doncs el significat del nom de Peratallada, resta evident per al qui visita la població. Peratallada va ser una de les poblacions catalanes més ben fortificades. El sistema defensiu era format per tres recintes de muralla (el principal amb el castell al centre i altres dos que eren al nord i llevant) protegida pel fossar excavat a la roca de cronologia ignorada i discutible. On actualment és visible, tenen una fondària d’uns 7 o 8 metres. Destaca el castell fortificat amb la seva torre de l'Homenatge i el palau (s. XI-XIV), les muralles (s. XII-XIII) i l'església de Sant Esteve (romànica de principis del segle XIII). Un fet curiós i que cal destacar és que Berenguer de Cruïlles (1310 - 1362), bisbe de Girona i primer president de la Generalitat de Catalunya era natural d'aquesta població.<br><br>El castell de Peratallada, al voltant del qual restà arrecerada la població, fou el centre de la baronia que pertanyia a l'esmentat llinatge dels Peratallada, documentats des del segle XI. El castell es comprova que existia el 1065, però algunes estructures arquitectòniques semblen demostrar que en aquest nucli ja hi va haver una fortalesa més antiga.<br><br>El monticle rocós s'aixeca 4 o 5 metres sobre el terreny que el rodeja. Al seu damunt s'enlaira el gran castell, amb la seva característica torre de l'Homenatge, i el magnífic palau, orientat a llevant, que dóna a la Plaça del Castell. També s'hi poden veure restes de merlets (espai per defensar-se entre la pedra massissa) que donen un gran atractiu i misticisme a la construcció. L'alta torre de l'Homenatge, la senya d'identitat del poble, és de planta rectangular, coronada per merlets quadrats. Té una porta adovellada i tenia un pis intermig de fusta. Va ser construïda amb filades de carreus escairats.",
                        "direccio" => "",
                        "poblacio" => "Peratallada",
                        "telefon" => 872987030,
                        "lat" => "41.9754531",
                        "lng" => "3.0872486",
                        "horari" =>"Obert 24 hores",
                        "preu" => "Gratis",
                        "web" => "www.visitperatallada.cat",
                        "email" => "turisme@forallac.cat",
                        "imatge" => "peratallada.jpg"
                    ),array(
                        "nom" => "Ruines arqueologiques de Sidillà",
                        "descripcio" => "Les restes de l’església preromànica i poblat de Sant Romà de Sidillà o de les Arenes són situades al terme municipal de Foixà. Per anar-hi cal agafar el camí que comunica aquest darrer poble amb Sant Llorenç de les Arenes. Aquest conjunt arqueològic es troba a uns tres quilòmetres de Foixà, prop d’una explotació d’extracció de sorra. Si bé en un primer tram el camí es indicat a la sortida de Foixà, posteriorment no es troba cap més indicador i l’indret és de molt mal trobar amagat per l’espessa vegetació de pins i de malesa<br><br>L’església de Sant Romà és d’una sola nau coberta amb volta de canó absis trapezial, arcs de ferradura i en molts llocs presenta un parament en opus spicatum. De l’antic poblat que hi havia a l’entorn del temple només s’ha excavat una part del sector de tramuntana de l’església on s’han posat al descobert la planta de diverses estances de les cases i s’hi ha trobat ceràmica datada entre els segles XI i XIII.<br><br>Les notícies més reculades que coneixem són de l’any 985 en que el lloc surt esmentada amb el nom de Siziliano. Al llarg de l’edat mitjana es esmentat amb diverses variants del nom sense que se’n trobi cap d’unànimement acceptada Ciziciliano, Ceziliano, Cidiliano o Sidilianum són alguns dels noms que hem trobat utilitzats. Fa molts anys que s’ha perdut el record d’aquesta denominació i la gent de la rodalia coneix aquestes ruïnes amb el nom de Sant Romanç.<br><br>L’església de Sant Romà tingué la consideració de parroquial i com a tal és esmentada en un document de l’any 1221. Malgrat que s’hagi dit que aquesta església i el lloc ja devien estar abandonats i deshabitats car no surten citats en els nomenclàtors oficials de la segona meitat del segle XIII i del XIV. Aquesta afirmació no és del certa ja què en un pergamí de l’any 1340 es capbrevada una casa dins la cellera de Sant Romà de Sant Llorenç de les Arenes (domum quam habemus et tenemus in cellaria Sancto Romani de Sancto Laurencio de Arenis). D’aquest escrit es pot deduir que el poble havia perdut ja la seva independència parroquial però que encara estava habitat.<br><br>Actualment aquest enclavament arqueològic està completament abandonat i envaït per la vegetació. Malgrat la importància que tenen aquestes ruïnes datades d’una època de la qual ens ha pervingut molt poques restes, l’oblit, la deixadesa i la degradació s’han apoderat del jaciment i no fan presagiar res de bo pel futur. Només ens cal desitjar que aquests mals auguris no es compleixin i que es pugui salvar per a les generacions futures un dels conjunts altmedievals més importants de Catalunya.",
                        "direccio" => "",
                        "poblacio" => "Foixà",
                        "telefon" => 972769259,
                        "lat" => "42.070535",
                        "lng" => "3.099800",
                        "horari" =>"Obert 24 hores",
                        "preu" => "Gratuit",
                        "web" => "www.foixa.cat",
                        "email" => "ajuntament@foixa.cat",
                        "imatge" => "Sidilla.jpg"
                    ),
);


$json_info_turisme = json_encode($info_turisme);

$f = fopen("informacio_turistica.json", "w+");
fwrite($f, $json_info_turisme);
fclose($f);



?>